// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Mention legale documents
 */
interface MentionLegaleDocumentData {
  /**
   * Titre field in *Mention legale*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Mentions legales
   * - **API ID Path**: mention_legale.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Contenu field in *Mention legale*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Saisir les mentions legales
   * - **API ID Path**: mention_legale.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Date de mise a jour field in *Mention legale*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: mention_legale.updated_at
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  updated_at: prismic.DateField;
}

/**
 * Mention legale document from Prismic
 *
 * - **API ID**: `mention_legale`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentionLegaleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MentionLegaleDocumentData>,
    "mention_legale",
    Lang
  >;

/**
 * Item in *Offre d'emploi → Technologies*
 */
export interface OffreEmploiDocumentDataTechnologiesItem {
  /**
   * Technologie field in *Offre d'emploi → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NextJS
   * - **API ID Path**: offre_emploi.technologies[].technology
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technology: prismic.KeyTextField;
}

/**
 * Content for Offre d'emploi documents
 */
interface OffreEmploiDocumentData {
  /**
   * Titre field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Developpeur Next.js
   * - **API ID Path**: offre_emploi.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Extrait field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Resume court
   * - **API ID Path**: offre_emploi.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Description field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description complete
   * - **API ID Path**: offre_emploi.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Entreprise field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nom de l'entreprise
   * - **API ID Path**: offre_emploi.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Localisation field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Paris / Remote
   * - **API ID Path**: offre_emploi.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Contrat field in *Offre d'emploi*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Type de contrat
   * - **API ID Path**: offre_emploi.contract
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contract: prismic.SelectField<
    "CDI" | "CDD" | "Freelance" | "Stage" | "Alternance"
  >;

  /**
   * Technologies field in *Offre d'emploi*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<OffreEmploiDocumentDataTechnologiesItem>
  >;
}

/**
 * Offre d'emploi document from Prismic
 *
 * - **API ID**: `offre_emploi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OffreEmploiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OffreEmploiDocumentData>,
    "offre_emploi",
    Lang
  >;

export type AllDocumentTypes = MentionLegaleDocument | OffreEmploiDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titre field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre de la section
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Sous-titre field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texte introductif
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Titre et sous-titre
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Banniere principale
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *OffersList → Default → Primary*
 */
export interface OffersListSliceDefaultPrimary {
  /**
   * Titre field in *OffersList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre du bloc
   * - **API ID Path**: offers_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for OffersList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Bloc listant les offres
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OffersListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OffersListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OffersList*
 */
type OffersListSliceVariation = OffersListSliceDefault;

/**
 * OffersList Shared Slice
 *
 * - **API ID**: `offers_list`
 * - **Description**: Liste des offres
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OffersListSlice = prismic.SharedSlice<
  "offers_list",
  OffersListSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Contenu field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Saisir du contenu
   * - **API ID Path**: text_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Texte riche
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: Bloc de texte libre
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MentionLegaleDocument,
      MentionLegaleDocumentData,
      OffreEmploiDocument,
      OffreEmploiDocumentData,
      OffreEmploiDocumentDataTechnologiesItem,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      OffersListSlice,
      OffersListSliceDefaultPrimary,
      OffersListSliceVariation,
      OffersListSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
