// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | HeroSlice
  | OffersListSlice
  | TextBlockSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Titre field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Accueil
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Image hero field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Legende hero field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nos dernieres opportunites
   * - **API ID Path**: homepage.hero_caption
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_caption: prismic.KeyTextField;

  /**
   * Introduction field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type ListeDocumentDataSlicesSlice = OffersListSlice | TextBlockSlice;

/**
 * Content for Liste documents
 */
interface ListeDocumentData {
  /**
   * Titre field in *Liste*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Offres d'emploi
   * - **API ID Path**: liste.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Introduction field in *Liste*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: liste.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Afficher le nuage de tags field in *Liste*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: liste.show_tag_cloud
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_tag_cloud: prismic.BooleanField;

  /**
   * Nombre d'offres par page field in *Liste*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 9
   * - **API ID Path**: liste.page_size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  page_size: prismic.NumberField;

  /**
   * Slice Zone field in *Liste*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: liste.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ListeDocumentDataSlicesSlice>;
}

/**
 * Liste document from Prismic
 *
 * - **API ID**: `liste`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ListeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ListeDocumentData>, "liste", Lang>;

/**
 * Content for Mentions Légales documents
 */
interface MentionsDocumentData {
  /**
   * Titre field in *Mentions Légales*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Mentions legales
   * - **API ID Path**: mentions.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Contenu field in *Mentions Légales*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentions.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Date de mise a jour field in *Mentions Légales*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: mentions.updated_at
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  updated_at: prismic.DateField;
}

/**
 * Mentions Légales document from Prismic
 *
 * - **API ID**: `mentions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MentionsDocumentData>,
    "mentions",
    Lang
  >;

/**
 * Item in *Offre d'emploi → Technologies*
 */
export interface OffreEmploiDocumentDataTechnologiesItem {
  /**
   * Technologie field in *Offre d'emploi → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NextJS
   * - **API ID Path**: offre_emploi.technologies[].technology
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technology: prismic.KeyTextField;
}

/**
 * Item in *Offre d'emploi → Emails administrateurs*
 */
export interface OffreEmploiDocumentDataAdminEmailsItem {
  /**
   * Email field in *Offre d'emploi → Emails administrateurs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: recrutement@example.com
   * - **API ID Path**: offre_emploi.admin_emails[].email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

/**
 * Content for Offre d'emploi documents
 */
interface OffreEmploiDocumentData {
  /**
   * Titre field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Developpeur Next.js
   * - **API ID Path**: offre_emploi.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Extrait field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Resume court
   * - **API ID Path**: offre_emploi.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Description field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description complete
   * - **API ID Path**: offre_emploi.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Entreprise field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nom de l'entreprise
   * - **API ID Path**: offre_emploi.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Localisation field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Paris / Remote
   * - **API ID Path**: offre_emploi.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Contrat field in *Offre d'emploi*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Type de contrat
   * - **API ID Path**: offre_emploi.contract
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contract: prismic.SelectField<
    "CDI" | "CDD" | "Freelance" | "Stage" | "Alternance"
  >;

  /**
   * Technologies field in *Offre d'emploi*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<OffreEmploiDocumentDataTechnologiesItem>
  >;

  /**
   * Emails administrateurs field in *Offre d'emploi*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.admin_emails[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  admin_emails: prismic.GroupField<
    Simplify<OffreEmploiDocumentDataAdminEmailsItem>
  >;
}

/**
 * Offre d'emploi document from Prismic
 *
 * - **API ID**: `offre_emploi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OffreEmploiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OffreEmploiDocumentData>,
    "offre_emploi",
    Lang
  >;

/**
 * Item in *Profil → Offres pinees*
 */
export interface ProfilDocumentDataPinnedOffersItem {
  /**
   * Offre field in *Profil → Offres pinees*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Selectionner une offre
   * - **API ID Path**: profil.pinned_offers[].offer
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  offer: prismic.ContentRelationshipField<"offre_emploi">;
}

type ProfilDocumentDataSlicesSlice = OffersListSlice | TextBlockSlice;

/**
 * Content for Profil documents
 */
interface ProfilDocumentData {
  /**
   * Titre field in *Profil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bienvenue
   * - **API ID Path**: profil.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Introduction field in *Profil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profil.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Titre bloc offres enregistrees field in *Profil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Offres enregistrees
   * - **API ID Path**: profil.saved_jobs_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  saved_jobs_title: prismic.KeyTextField;

  /**
   * Offres pinees field in *Profil*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: profil.pinned_offers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pinned_offers: prismic.GroupField<
    Simplify<ProfilDocumentDataPinnedOffersItem>
  >;

  /**
   * Titre historique field in *Profil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Historique des candidatures
   * - **API ID Path**: profil.history_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  history_title: prismic.KeyTextField;

  /**
   * Texte historique field in *Profil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profil.history_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  history_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Profil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: profil.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProfilDocumentDataSlicesSlice>;
}

/**
 * Profil document from Prismic
 *
 * - **API ID**: `profil`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfilDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProfilDocumentData>,
    "profil",
    Lang
  >;

type SingleDocumentDataSlicesSlice = TextBlockSlice;

/**
 * Content for Single documents
 */
interface SingleDocumentData {
  /**
   * Titre field in *Single*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Developpeur NextJS
   * - **API ID Path**: single.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Offre associee field in *Single*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Selectionner une offre
   * - **API ID Path**: single.offre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  offre: prismic.ContentRelationshipField<"offre_emploi">;

  /**
   * Texte introductif field in *Single*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single.job_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  job_intro: prismic.RichTextField;

  /**
   * Afficher le formulaire field in *Single*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: single.show_apply_form
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_apply_form: prismic.BooleanField;

  /**
   * Slice Zone field in *Single*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: single.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SingleDocumentDataSlicesSlice>;
}

/**
 * Single document from Prismic
 *
 * - **API ID**: `single`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SingleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SingleDocumentData>, "single", Lang>;

type TagDocumentDataSlicesSlice = OffersListSlice | TextBlockSlice;

/**
 * Content for Tag documents
 */
interface TagDocumentData {
  /**
   * Titre field in *Tag*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Techno
   * - **API ID Path**: tag.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Nom du tag field in *Tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NextJS
   * - **API ID Path**: tag.tag_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_name: prismic.KeyTextField;

  /**
   * Introduction field in *Tag*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Slice Zone field in *Tag*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TagDocumentDataSlicesSlice>;
}

/**
 * Tag document from Prismic
 *
 * - **API ID**: `tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TagDocumentData>, "tag", Lang>;

export type AllDocumentTypes =
  | HomepageDocument
  | ListeDocument
  | MentionsDocument
  | OffreEmploiDocument
  | ProfilDocument
  | SingleDocument
  | TagDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titre field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre de la section
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Sous-titre field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texte introductif
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Titre et sous-titre
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Banniere principale
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *OffersList → Default → Primary*
 */
export interface OffersListSliceDefaultPrimary {
  /**
   * Titre field in *OffersList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre du bloc
   * - **API ID Path**: offers_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for OffersList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Bloc listant les offres
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OffersListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OffersListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OffersList*
 */
type OffersListSliceVariation = OffersListSliceDefault;

/**
 * OffersList Shared Slice
 *
 * - **API ID**: `offers_list`
 * - **Description**: Liste des offres
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OffersListSlice = prismic.SharedSlice<
  "offers_list",
  OffersListSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Contenu field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Saisir du contenu
   * - **API ID Path**: text_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Texte riche
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: Bloc de texte libre
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ListeDocument,
      ListeDocumentData,
      ListeDocumentDataSlicesSlice,
      MentionsDocument,
      MentionsDocumentData,
      OffreEmploiDocument,
      OffreEmploiDocumentData,
      OffreEmploiDocumentDataTechnologiesItem,
      OffreEmploiDocumentDataAdminEmailsItem,
      ProfilDocument,
      ProfilDocumentData,
      ProfilDocumentDataPinnedOffersItem,
      ProfilDocumentDataSlicesSlice,
      SingleDocument,
      SingleDocumentData,
      SingleDocumentDataSlicesSlice,
      TagDocument,
      TagDocumentData,
      TagDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      OffersListSlice,
      OffersListSliceDefaultPrimary,
      OffersListSliceVariation,
      OffersListSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
